.TH SDCPPOLD 1 
.SH NAME
sdcppold \- C preprocessor for SDCC
.SH SYNOPSIS
.B sdcppold
.I "[options] filename"
.SH "DESCRIPTION"
This manual page documents briefly the
.BR sdccpold
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Instead, you can read the documentation in
/usr/share/doc/sdcc.
.PP
.B SDCC
is a Freeware, retargettable, optimizing ANSI-C compiler
designed for 8 bit Microprocessors.
.SH OPTIONS
The two following options will give you the list of options:
.TP
.B \-h
Show summary of options.
.TP
.B \--version
Show version of program as well as options.
.SH AUTHOR
This manual page was written by Aurelien Jarno <aurelien@aurel32.net>,
for the Debian GNU/Linux system (but may be used by others).
